### ISSUE TITLE
Support DynamoDB as a metadata store

### ISSUE THREAD

**Issue by mosuka** [mosuka/phalanx#69]

**Comment by wolfeidau** [comment]
I am happy to help with this if needed, I have written https://github.com/wolfeidau/dynalock and worked on other locking projects using dynamodb.

**Comment by mosuka** [comment]
@wolfeidau 
Thank you.
Since you seem to be familiar with DynamoDB, this issue will be very easy for you.
I am looking forward to your pull request.

It would be great if you could develop it same as the implementation of etcd here.
https://github.com/mosuka/phalanx/blob/main/metastore/storage.go
https://github.com/mosuka/phalanx/blob/main/metastore/storage_etcd.go

**Comment by wolfeidau** [comment]
I started work on this in #74 the documentation helps a lot.

**Comment by mosuka** [comment]
@wolfeidau Thank you for your contribution! :smile:
